server:
  port: 8082


#logging:
#  level:
#    com.crq.content.openfeign.UserService: debug
#spring:
#  sleuth:
#    sampler:
#      probability: 1.0
#      rate: 1000
#  zipkin:
#    sender:
#      type: rabbit
#    rabbitmq:
#      addresses: localhost:5672
#      queue: zipkin

