server:
  port: 8081

spring:
  application:
    name: user-center
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 139.196.153.80:8848
      username: nacos
      password: nacos
  datasource:
    url: jdbc:mysql://localhost:3306/share?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver